name: water_pollution_app
description: A Flutter app to report and track water pollution incidents
publish_to: 'none' # Remove if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # App functionality
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  # Launcher icons generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/water-pollution.png

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/water-pollution.png"
